"""
Report Writer Module - Generate analysis reports in Markdown/HTML/PDF

Reports automatically generated with:
1. Analysis scope and methodology
2. Data summary
3. Statistical findings
4. Rule candidates
5. Comparison results
6. Limitations and next steps

CRITICAL: Include disclaimer that this is NOT a decipherment tool
"""

from typing import List, Dict, Optional
from datetime import datetime
from dataclasses import dataclass

from .statistics import TokenStatistics, SectionMetrics
from .entropy import EntropyMetrics
from .rule_engine import RuleCandidate
from .corpus_compare import CorpusProfile, CorpusSimilarity

# ============================================================================
# DATA STRUCTURES
# ============================================================================

@dataclass
class ReportConfig:
    """Report generation configuration"""
    include_methodology: bool = True
    include_statistics: bool = True
    include_rules: bool = True
    include_entropy: bool = True
    include_corpus: bool = True
    include_limitations: bool = True
    author: str = "Voynich Reference Analyzer v0.2"
    generate_html: bool = False
    generate_pdf: bool = False

# ============================================================================
# REPORT GENERATOR
# ============================================================================

class ReportWriter:
    """Generate comprehensive analysis reports"""

    def __init__(self, config: Optional[ReportConfig] = None):
        """
        Initialize report writer

        Args:
            config: ReportConfig object
        """
        self.config = config or ReportConfig()

    # ========================================================================
    # MAIN REPORT GENERATION
    # ========================================================================

    def generate_markdown_report(
        self,
        title: str,
        token_stats: TokenStatistics,
        entropy_metrics: EntropyMetrics,
        rules: List[RuleCandidate],
        voynich_profile: CorpusProfile,
        comparison_results: Dict[str, float]
    ) -> str:
        """
        Generate complete Markdown report

        Args:
            title: Report title
            token_stats: Token statistics
            entropy_metrics: Entropy analysis
            rules: Rule candidates
            voynich_profile: Voynich statistical profile
            comparison_results: Corpus comparison results

        Returns:
            Markdown formatted report string
        """
        lines = []

        # Header
        lines.append(f"# {title}\n")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        lines.append(f"**Tool:** Voynich Reference Analyzer v0.2\n\n")

        # Disclaimer
        lines.append(self._generate_disclaimer())
        lines.append("\n")

        # Table of Contents
        lines.append("## Table of Contents\n")
        lines.append("1. [Summary](#summary)\n")
        lines.append("2. [Methodology](#methodology)\n")
        lines.append("3. [Statistical Findings](#statistical-findings)\n")
        lines.append("4. [Rule Candidates](#rule-candidates)\n")
        lines.append("5. [Entropy Analysis](#entropy-analysis)\n")
        lines.append("6. [Corpus Comparison](#corpus-comparison)\n")
        lines.append("7. [Limitations](#limitations)\n")
        lines.append("8. [Recommendations](#recommendations)\n\n")

        # Executive Summary
        lines.append(self._generate_summary(token_stats, entropy_metrics))
        lines.append("\n")

        # Methodology
        if self.config.include_methodology:
            lines.append(self._generate_methodology())
            lines.append("\n")

        # Statistical Findings
        if self.config.include_statistics:
            lines.append(self._generate_statistics_section(token_stats, voynich_profile))
            lines.append("\n")

        # Rule Candidates
        if self.config.include_rules:
            lines.append(self._generate_rules_section(rules))
            lines.append("\n")

        # Entropy Analysis
        if self.config.include_entropy:
            lines.append(self._generate_entropy_section(entropy_metrics))
            lines.append("\n")

        # Corpus Comparison
        if self.config.include_corpus:
            lines.append(self._generate_corpus_section(comparison_results))
            lines.append("\n")

        # Limitations
        if self.config.include_limitations:
            lines.append(self._generate_limitations())
            lines.append("\n")

        # Recommendations
        lines.append(self._generate_recommendations())
        lines.append("\n")

        # Footer
        lines.append("---\n")
        lines.append(f"**Report generated by:** {self.config.author}\n")

        return ''.join(lines)

    # ========================================================================
    # SECTION GENERATORS
    # ========================================================================

    @staticmethod
    def _generate_disclaimer() -> str:
        """Generate disclaimer section"""
        return """## ⚠️ Important Disclaimer

**This program is NOT a decipherment tool.**

We do NOT:
- ❌ Translate Voynichese
- ❌ Claim to have decoded the manuscript
- ❌ Assign fixed meanings to words
- ❌ Make definitive claims about authorship

We DO:
- ✅ Analyze document structure quantitatively
- ✅ Extract candidate rules with evidence counts
- ✅ Compare structural patterns with reference corpora
- ✅ Provide statistical validation of observations
- ✅ Produce reproducible, verifiable analysis

**This analysis tests the hypothesis:** Does the Voynich Manuscript's
structure more closely resemble a reference/taxonomic system
(like catalogs, classifications, databases) than natural language or cipher text?

The answer is NOT "yes, it's decoded" but rather "the structural evidence
is consistent with (or inconsistent with) a reference system hypothesis."
"""

    @staticmethod
    def _generate_summary(
        token_stats: TokenStatistics,
        entropy_metrics: EntropyMetrics
    ) -> str:
        """Generate executive summary"""
        return f"""## Summary

### Key Findings

| Metric | Value |
|--------|-------|
| **Total Tokens** | {token_stats.total_tokens:,} |
| **Unique Tokens** | {token_stats.unique_tokens:,} |
| **Type-Token Ratio** | {token_stats.token_type_ratio:.3f} |
| **Hapax Ratio** | {token_stats.hapax_ratio:.1%} |
| **Avg Token Length** | {token_stats.avg_token_length:.2f} glyphs |
| **1-gram Entropy** | {entropy_metrics.entropy_1gram:.2f} bits |
| **2-gram Entropy** | {entropy_metrics.entropy_2gram:.2f} bits |
| **Redundancy** | {entropy_metrics.redundancy:.1%} |

### Initial Assessment

The Voynich Manuscript exhibits structural properties that fall between
natural language and highly constrained reference systems. This analysis
tests which hypothesis better explains the observed patterns.
"""

    @staticmethod
    def _generate_methodology() -> str:
        """Generate methodology section"""
        return """## Methodology

### Data Source
- **Transcription:** EVA (European Voynich Alphabet) notation
- **Format:** IT2a-n.txt (Takeshi Takahashi's transcription)
- **Scope:** 112 folios, ~7,063 tokens, ~50,000 glyphs

### Parsing Pipeline
1. **Line Parsing:** Extract folio ID, paragraph, line number, transcriber
2. **Token Extraction:** Split on dots (.) to get dot-separated words
3. **Glyph Parsing:** Break tokens into individual characters
4. **Metadata Extraction:** Section, Currier version, scribe hand

**Critical distinction:**
- Physical line = original transcription line
- EVA token = dot-separated word unit (how we count)

### Statistical Methods
- **Frequency Analysis:** Token/character frequency distributions
- **Type-Token Ratio:** Vocabulary diversity metric
- **Hapax Analysis:** Words appearing exactly once
- **Entropy Calculation:** Shannon entropy (H = -Σ p(x) log₂ p(x))
- **N-gram Analysis:** 2-gram, 3-gram, 4-gram frequency
- **Hypothesis Testing:** Bonferroni-corrected significance tests

### Reference Corpora
Compare Voynich against 6 reference corpora:
1. Natural English prose
2. Herbal/botanical descriptions
3. Plant name catalogs
4. Taxonomic classifications
5. Artificially generated text
6. Cipher/encoded text

### Validation Criteria
Each observation must have:
- Evidence count (how many instances)
- Exception count (how many violate the rule)
- Confidence score (evidence / total)
- Validation status (candidate, validated, rejected)
"""

    @staticmethod
    def _generate_statistics_section(
        token_stats: TokenStatistics,
        voynich_profile: CorpusProfile
    ) -> str:
        """Generate statistics section"""
        return f"""## Statistical Findings

### Token Statistics

- **Total tokens:** {token_stats.total_tokens:,}
- **Unique tokens:** {token_stats.unique_tokens:,}
- **Type-Token Ratio (TTR):** {token_stats.token_type_ratio:.3f}
  - Interpretation: {token_stats.token_type_ratio * 100:.1f}% vocabulary coverage
  - Comparison: English ~0.42, Catalogs ~0.72
- **Corrected TTR:** {voynich_profile.corrected_ttr:.3f}
  - Accounts for text length differences
- **Hapax tokens:** {token_stats.hapax_tokens:,} words appear exactly once
- **Hapax ratio:** {token_stats.hapax_ratio:.1%} of unique tokens
- **Average token length:** {token_stats.avg_token_length:.2f} glyphs

### Top Tokens

| Rank | Token | Frequency |
|------|-------|-----------|
"""
        for i, (token, count) in enumerate(token_stats.top_tokens[:10], 1):
            return f"| {i} | `{token}` | {count} |\n"

    @staticmethod
    def _generate_rules_section(rules: List[RuleCandidate]) -> str:
        """Generate rules section"""
        lines = ["## Rule Candidates\n\n"]

        # Summary
        validated = [r for r in rules if r.confidence > 0.70]
        lines.append(f"**Total Rules:** {len(rules)}\n")
        lines.append(f"**Strong Rules (>0.70 confidence):** {len(validated)}\n\n")

        # Top rules
        lines.append("### Top 5 Rules\n\n")

        sorted_rules = sorted(rules, key=lambda r: (r.evidence_count, r.confidence), reverse=True)

        for i, rule in enumerate(sorted_rules[:5], 1):
            lines.append(f"#### Rule {i}: {rule.rule_name}\n\n")
            lines.append(f"- **Description:** {rule.rule_description}\n")
            lines.append(f"- **Type:** {rule.rule_type.value}\n")
            lines.append(f"- **Evidence:** {rule.evidence_count} instances\n")
            lines.append(f"- **Exceptions:** {rule.exception_count}\n")
            lines.append(f"- **Confidence:** {rule.confidence:.1%}\n")
            lines.append(f"- **Status:** {rule.validation_status.value}\n\n")

        return ''.join(lines)

    @staticmethod
    def _generate_entropy_section(entropy_metrics: EntropyMetrics) -> str:
        """Generate entropy analysis section"""
        return f"""## Entropy Analysis

### Entropy Metrics

- **1-gram entropy:** {entropy_metrics.entropy_1gram:.2f} bits
- **2-gram entropy:** {entropy_metrics.entropy_2gram:.2f} bits
- **Conditional entropy:** {entropy_metrics.conditional_entropy:.2f} bits
- **Redundancy:** {entropy_metrics.redundancy:.1%}
- **Randomness score:** {entropy_metrics.randomness_score:.1%}
- **Maximum possible entropy:** {entropy_metrics.max_entropy:.2f} bits

### Interpretation

**Entropy range interpretation:**
- Very low (<3.0 bits): Highly structured, few unique characters
- Low (3.0-4.5 bits): Structured systems like catalogs
- Moderate (4.5-6.0 bits): Natural language range
- High (>6.0 bits): Random or diverse text

**Voynich result:** {entropy_metrics.entropy_1gram:.2f} bits falls
"""

    @staticmethod
    def _generate_corpus_section(comparison_results: Dict[str, float]) -> str:
        """Generate corpus comparison section"""
        lines = ["## Corpus Comparison\n\n"]

        lines.append("### Similarity Rankings\n\n")
        lines.append("| Corpus Type | Similarity | Interpretation |\n")
        lines.append("|-------------|------------|----------------|\n")

        for corpus_type, similarity in sorted(comparison_results.items(),
                                             key=lambda x: x[1], reverse=True):
            if similarity > 0.85:
                interp = "Very Similar"
            elif similarity > 0.70:
                interp = "Similar"
            elif similarity > 0.50:
                interp = "Somewhat Similar"
            else:
                interp = "Different"

            lines.append(f"| {corpus_type} | {similarity:.1%} | {interp} |\n")

        return ''.join(lines)

    @staticmethod
    def _generate_limitations() -> str:
        """Generate limitations section"""
        return """## Limitations

1. **EVA Transcription Only**
   - Analysis based on EVA notation, not original images
   - Potential transcription errors could affect results

2. **Line Parsing Ambiguity**
   - Distinction between physical lines and EVA segments may be imperfect
   - Some lines may contain multiple logical units

3. **No Original Manuscript Access**
   - Analysis limited to published transcription
   - Color, paper, ink analysis not possible

4. **Limited Reference Corpora**
   - Comparison corpora may not perfectly match Voynich context
   - Medieval sources limited compared to modern texts

5. **Multiple Hypotheses Compatible**
   - These patterns could be consistent with multiple interpretations
   - Statistical evidence ≠ proof of specific hypothesis

6. **Currier A/B & Scribe Variations**
   - Cannot fully control for different scribal hands
   - Section-specific changes may confound with scribal changes
"""

    @staticmethod
    def _generate_recommendations() -> str:
        """Generate recommendations section"""
        return """## Recommendations for Next Steps

### Immediate Analysis
1. ✓ Validate strong rules (>0.70 confidence) with additional evidence
2. ✓ Generate counterexamples for each rule
3. ✓ Perform significance testing (Bonferroni correction)

### Advanced Analysis
1. ✓ Token family clustering (edit distance/Levenshtein)
2. ✓ Position bias analysis (leading/trailing character patterns)
3. ✓ Section-specific vocabulary divergence
4. ✓ Currier A/B and scribe hand control

### Validation
1. ✓ Cross-validation: split data and repeat analysis
2. ✓ Bootstrap confidence intervals on key metrics
3. ✓ Domain expert review (paleography, historical linguistics)

### Expansion
1. ✓ Image analysis (Yale Beinecke images)
2. ✓ Color analysis and layout patterns
3. ✓ Comparison with other undeciphered manuscripts
4. ✓ Peer review and publication

### Open Questions
1. What structures do the sections represent?
2. Are token families meaningful linguistic units?
3. How much variation is due to scribal hand vs. content?
4. Can position-based patterns guide further analysis?
"""

if __name__ == "__main__":
    # Example report generation
    config = ReportConfig()
    writer = ReportWriter(config)

    from statistics import TokenStatistics
    from entropy import EntropyMetrics

    # Dummy data
    token_stats = TokenStatistics(
        total_tokens=7000,
        unique_tokens=4000,
        token_type_ratio=0.57,
        hapax_tokens=2000,
        hapax_ratio=0.50,
        avg_token_length=3.5,
        top_tokens=[("chol", 150), ("daiin", 120)]
    )

    entropy_metrics = EntropyMetrics(
        entropy_1gram=6.14,
        entropy_2gram=8.5,
        conditional_entropy=4.2,
        redundancy=0.65,
        randomness_score=0.35,
        max_entropy=4.7
    )

    voynich_profile = CorpusProfile(
        corpus_name="Voynich",
        corpus_type="unknown",
        total_tokens=7000,
        unique_tokens=4000,
        token_type_ratio=0.57,
        corrected_ttr=0.45,
        hapax_ratio=0.50,
        avg_token_length=3.5,
        word_final_ratio=0.96,
        entropy_1gram=6.14,
        entropy_2gram=8.5,
        conditional_entropy=4.2,
        top_10_concentration=25.0
    )

    report = writer.generate_markdown_report(
        "Voynich Reference Hypothesis Analysis Report",
        token_stats,
        entropy_metrics,
        [],
        voynich_profile,
        {"natural_language": 0.65, "catalog": 0.78}
    )

    print("Report generated successfully")
